### ISSUE TITLE
Integrate Welcome Bot

### ISSUE THREAD

**Issue by muthuannamalai12** [ritwikranjan/College-Community#4]
I can add a welcome bot config file having a proper message that will show up when any user will open up an issue or pull-request for the first time.
For reference, check out: https://github.com/apps/welcome

Please assign it to me as a part of Cross Woc

**Comment by seemantaggarwal** [comment]
Sure, open a PR, and if like the changes, I'll merge and assign

**Comment by muthuannamalai12** [comment]
@seemantaggarwal I have opened a PR for this issue. Kindly review it

**Comment by ritwikranjan** [comment]
PR merged successfully
