### ISSUE TITLE
Create Code of Conduct

### ISSUE THREAD

**Issue by muthuannamalai12** [ritwikranjan/College-Community#5]
I would like to add code of conduct file as code of conduct is a necessary file which the contributors need to follow so that everyone follows a decorum.

**Comment by muthuannamalai12** [comment]
I would love to work on this issue as a part of Cross-woc. Kindly assign it to me.

**Comment by seemantaggarwal** [comment]
Sure, will be assigned soon, working on it

**Comment by muthuannamalai12** [comment]
> Sure, will be assigned soon, working on it

Can I create a PR for this??

**Comment by seemantaggarwal** [comment]
It is assigned to you as easy PR, for 100 points

**Comment by seemantaggarwal** [comment]
Tags will be added by @ritwikranjan

**Comment by muthuannamalai12** [comment]
> Tags will be added by @ritwikranjan

Thank you
